### ISSUE TITLE
Culled clones collide with each other

### ISSUE THREAD

**Issue by 43082ujfgrj** [cortex-command-community/Cortex-Command-Community-Project#105]
**Describe the bug**
all types of culled clones seem to collide with each other in some spot which results in weird pyramids if you stack them
![image](https://github.com/cortex-command-community/Cortex-Command-Community-Project/assets/155900968/5fe6ebeb-6b61-4d7b-84af-17fa43211f83)

**To Reproduce**
order a lot of culled clones (they will probably die already if dropshipped because of the collision)

**Additional context**
latest 6.1
ff / friendly collisions is turned OFF, if it was on they'd be all dead

**Comment by Causeless** [comment]
This is intentional behaviour, it's so they can all climb over each other en masse to get over walls and other obstacles (due to their lack of jetpacks)
