### ISSUE TITLE
README.md points to stale downloads location

### ISSUE THREAD

**Issue by janisozaur** [cortex-command-community/Cortex-Command-Community-Project#36]
https://github.com/cortex-command-community/Cortex-Command-Community-Project/blob/development/README.md#L12 points to https://github.com/cortex-command-community/Cortex-Command-Community.github.io/blob/d7fa4c95ebffdda9d08ea765300bdb45842c9d15/src/components/Static/Downloads/Downloads.js#L15 which is an archived project.

**Comment by Causeless** [comment]
@traunts Can we get releases shifted into the monorepo?

**Comment by Causeless** [comment]
Fixed
