### ISSUE TITLE
ThreadedUpdate still runs on items in inventory

### ISSUE THREAD

**Issue by pawnishoovy** [cortex-command-community/Cortex-Command-Community-Project#57]
**Describe the bug**
ThreadedUpdate still runs on items in inventory.

**To Reproduce**
1. Have a gun with ThreadedUpdate that prints every frame for example
2. Put the gun in inventory
3. See as the code and prints still happen

**Expected behavior**
ThreadedUpdate should stop running in items in inventory, just like Update does.

**Comment by Causeless** [comment]
528c4bc7f6017971a36be0252fce61609a3a2be2
