### ISSUE TITLE
[6.1] Nucleo gun crashes my game

### ISSUE THREAD

**Issue by onelikeandidie** [cortex-command-community/Cortex-Command-Community-Project#91]
**Describe the bug**
The Nucleo gun crashes my game consistently.

**To Reproduce**
1. Go to Test Activity
2. Place a Nucleo gun
3. Fire the gun
4. Game Crashes

**Screenshots**
Here's footage of the bug happening in 2 scenarios

Just the nucleo gun test
https://www.youtube.com/watch?v=dWbrk_mq3LU

Footage of me investigating the bug before I knew what gun it was
https://www.youtube.com/watch?v=gdT9S5JJ_6E

**Additional context**
When running in the terminal, I can see the following output when it crashes:
```bash
libpng warning: iCCP: known incorrect sRGB profile
CortexCommand.AppImage: ../external/sources/luabind-0.7.1/src/class_rep.cpp:1493: void* luabind::detail::class_rep::convert_to(const std::type_info*, const luabind::detail::object_rep*, void*) const: Assertion `(steps >= 0) && "internal error, please report"' failed.
zsh: IOT instruction (core dumped)  ./CortexCommand.AppImage
```

I am running the AppImage of 6.1. My system specs are:
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.12
Kernel Version: 6.6.10-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 3600X 6-Core Processor
Memory: 31,2 GiB of RAM
Graphics Processor: AMD Radeon RX 7900 XT
Manufacturer: ASUS

**Comment by onelikeandidie** [comment]
I just cloned the game and compiled locally. The game now does not crash through the compiled binaries. Maybe it's an AppImage issue?

**Comment by onelikeandidie** [comment]
Scratch that, I compile the debug version with `meson setup --buildtype=debug build && ninja -C build` and that worked fine but compiling the non-debug version now crashes the game????? I am so confused, how does that make a difference? I'll make a little footage on this.

**Comment by onelikeandidie** [comment]
Here footage of compiling both debug and non-debug (WARNING: Boring Footage) and the bug only happening on non-debug version.
https://youtu.be/BOOATvxzkA8

**Comment by onelikeandidie** [comment]
I tried to debug this but I don't really understand how this codebase works, I'm going to try a little longer to see if I can get somewhere

**Comment by Causeless** [comment]
This should be fixed by 1121b46c730db94652fb4a0ac90936a9d57942b4. Can you confirm you are running with this?

**Comment by onelikeandidie** [comment]
Can confirm, that fixes the issue! Thank you very much :)

**Comment by onelikeandidie** [comment]
Forgot to close the issue

**Comment by onelikeandidie** [comment]
I was checked out on tag v6.1.0 so I didn't have the latest stuff
