### ISSUE TITLE
PathFinder::CalculatePath() crash

### ISSUE THREAD

**Issue by MyNameIsTrez** [cortex-command-community/Cortex-Command-Community-Project#92]
**Describe the bug**
The game crashes in `PathFinder::CalculatePath()` in release 6.1 when Gotcha's converted Vault-Tec mod is used:
![image](https://github.com/cortex-command-community/Cortex-Command-Community-Project/assets/32989873/056d5b3c-aa42-4714-9b71-c370f8dc4d27)

You need to launch with `msbuild Debug (Release)`. `Minimal` for some reason points to a totally different line, so can't be used.

**To Reproduce**
1. Download [Vault-Tec.rte.zip](https://github.com/cortex-command-community/Cortex-Command-Community-Project/files/14322936/Vault-Tec.rte.zip)
2. Download [Benchmark.rte.zip](https://github.com/cortex-command-community/Cortex-Command-Community-Project/files/14322938/Benchmark.rte.zip)
3. Use this in your Settings.ini to instantly have the issue printed when the game boots:
```ini
	LaunchIntoActivity = 1
	DefaultActivityType = GAScripted
	DefaultActivityName = Combat Benchmark
	DefaultSceneName = Benchmark
```

**Comment by Causeless** [comment]
Can you test this on latest development? I suspect this may be fixed.

**Comment by Causeless** [comment]
It's not fixed... testing.

**Comment by Causeless** [comment]
The allegro assert in Debug Minimal is a result of unindexed sprites

**Comment by Causeless** [comment]
Issue is from VaultTec, for some reason, applying a team value of 6 to an actor. Added a workaround to avoid this issue in d246d36bc9393f1ccd988c30d1e5c796563b4a24.
