### ISSUE TITLE
msbuild Debug (Full) fails to compile

### ISSUE THREAD

**Issue by MyNameIsTrez** [cortex-command-community/Cortex-Command-Community-Project#93]
**Describe the bug**
`msbuild Debug (Full)` fails to compile on the latest development commit (8112e60fe99d24db98892c36e6bcd39a775bb458):
`'/O2' and '/RTC1' command-line options are incompatible`

the full error is this:
`"I:\Programming\Cortex-Command-Community-Project\RTEA.sln" (default target) (1) -> "I:\Programming\Cortex-Command-Community-Project\RTEA.vcxproj" (default target) (2) -> (ClCompile target) -> cl : command line  error D8016: '/O2' and '/RTC1' command-line options are incompatible [I:\Programming\Cortex-Command-Community-Project\RTEA.vcxproj]`

All other `msbuild Debug` variants compile fine.

**Comment by Causeless** [comment]
5f9c0e25a8a596fa42087b225cab73af804493a8 fixes this. Some other Tracy issues but looking into those now
