### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION crash, the parameter is incorrect

### ISSUE THREAD

**Issue by MyNameIsTrez** [cortex-command-community/Cortex-Command-Community-Project#98]
**Describe the bug**
This issue happens in both Release 6.1 and the latest Development branch. I haven't tested whether it happens in Pre5.

I've seen this error discussed before these past few days, I think about vanilla.

![image](https://github.com/cortex-command-community/Cortex-Command-Community-Project/assets/32989873/5f2fb4da-0e22-4539-b00b-1774820b4bea)

**To Reproduce**
You may need to run the game for a few minutes, and reload it a few times, in order for the crash to happen.

1. Download [CIS.rte.zip](https://github.com/cortex-command-community/Cortex-Command-Community-Project/files/14324359/CIS.rte.zip)
2. Download [Benchmark.rte.zip](https://github.com/cortex-command-community/Cortex-Command-Community-Project/files/14324357/Benchmark.rte.zip)
3. Use this in your Settings.ini to instantly have the issue printed when the game boots:
```ini
	LaunchIntoActivity = 1
	DefaultActivityType = GAScripted
	DefaultActivityName = Combat Benchmark
	DefaultSceneName = Benchmark
```

**Comment by Causeless** [comment]
Fixed in cfcd56d5c6ef5662fea4ab970b19e5499da9d690
